"""Initial schema

Revision ID: 3b3e93afddbc
Revises:
Create Date: 2025-12-16 20:57:48.814348

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3b3e93afddbc"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Create schema if it doesn't exist
    op.execute("CREATE SCHEMA IF NOT EXISTS auth")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("is_system_user", sa.Boolean(), nullable=False),
        sa.Column("is_first_user", sa.Boolean(), nullable=False),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("email_verification_token", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="auth",
    )
    with op.batch_alter_table("users", schema="auth") as batch_op:
        batch_op.create_index(batch_op.f("ix_auth_users_email"), ["email"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_auth_users_email_verified"), ["email_verified"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_auth_users_role"), ["role"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_auth_users_username"), ["username"], unique=True
        )

    op.create_table(
        "password_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="auth",
    )
    with op.batch_alter_table("password_history", schema="auth") as batch_op:
        batch_op.create_index(
            batch_op.f("ix_auth_password_history_created_at"),
            ["created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_auth_password_history_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="auth",
    )
    with op.batch_alter_table("refresh_tokens", schema="auth") as batch_op:
        batch_op.create_index(
            batch_op.f("ix_auth_refresh_tokens_expires_at"),
            ["expires_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_auth_refresh_tokens_token_hash"), ["token_hash"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_auth_refresh_tokens_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "token_blacklist",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("token_id", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="auth",
    )
    with op.batch_alter_table("token_blacklist", schema="auth") as batch_op:
        batch_op.create_index(
            batch_op.f("ix_auth_token_blacklist_expires_at"),
            ["expires_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_auth_token_blacklist_token_id"), ["token_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("token_blacklist", schema="auth") as batch_op:
        batch_op.drop_index(batch_op.f("ix_auth_token_blacklist_token_id"))
        batch_op.drop_index(batch_op.f("ix_auth_token_blacklist_expires_at"))

    op.drop_table("token_blacklist", schema="auth")
    with op.batch_alter_table("refresh_tokens", schema="auth") as batch_op:
        batch_op.drop_index(batch_op.f("ix_auth_refresh_tokens_user_id"))
        batch_op.drop_index(batch_op.f("ix_auth_refresh_tokens_token_hash"))
        batch_op.drop_index(batch_op.f("ix_auth_refresh_tokens_expires_at"))

    op.drop_table("refresh_tokens", schema="auth")
    with op.batch_alter_table("password_history", schema="auth") as batch_op:
        batch_op.drop_index(batch_op.f("ix_auth_password_history_user_id"))
        batch_op.drop_index(batch_op.f("ix_auth_password_history_created_at"))

    op.drop_table("password_history", schema="auth")
    with op.batch_alter_table("users", schema="auth") as batch_op:
        batch_op.drop_index(batch_op.f("ix_auth_users_username"))
        batch_op.drop_index(batch_op.f("ix_auth_users_role"))
        batch_op.drop_index(batch_op.f("ix_auth_users_email_verified"))
        batch_op.drop_index(batch_op.f("ix_auth_users_email"))

    op.drop_table("users", schema="auth")
    # ### end Alembic commands ###
